apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: kleeat-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: Zoznam čakajúcich xszenasi # napr. "Zoznam čakajúcich <pfx>"
  description: "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii" # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Levente Szénasi" # Zadajte mená autorov
  azureLink: "https://kleeat-ambulance-chh3fqetbfbhd5dr.westeurope-01.azurewebsites.net"
  frontendRepoUrl: "https://github.com/Kleeat/ambulance-ufe"
  backendRepoUrl: "https://github.com/Kleeat/ambulance-webapi"
  gitopsRepoUrl: "https://github.com/Kleeat/ambulance-gitops"
