apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: kleeat-ambulance-ufe-content
spec:
  microFrontend: kleeat-ambulance-ufe
  element: kleeat-ambulance-wl-app
  attributes:
    - name: api-base
      value: /kleeat-api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: ./kleeat-ambulance-wl/
  displayRules:
    - allOf:
        - context-name: main-content
        - path: "^(\\.?/)?kleeat-ambulance-wl(/.*)?$"
