apiVersion: apps/v1
kind: Deployment
metadata:
  name: kleeat-ambulance-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /kleeat-openapi
            - name: BASE_URL
              value: /kleeat-openapi-ui
